[tool.poetry]
name = "kolomon-backend"
version = "0.1.0"
description = "A backend for Stari kolomoni project"
authors = ["Grimpy101, DefaultSimon"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.6"
psycopg2 = "^2.9.1"
djangorestframework = "^3.12.4"
Markdown = "^3.3.4"
django-filter = "^2.4.0"
djangorestframework-simplejwt = "^4.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
