"""Links 2

Revision ID: 3b81be27e52c
Revises: aade61970e7a
Create Date: 2022-02-15 18:42:14.847211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b81be27e52c'
down_revision = 'aade61970e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('entry_id', sa.Integer(), nullable=True))
    op.drop_constraint('links_entry_fkey', 'links', type_='foreignkey')
    op.create_foreign_key(None, 'links', 'entries', ['entry_id'], ['id'])
    op.drop_column('links', 'entry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('entry', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.create_foreign_key('links_entry_fkey', 'links', 'entries', ['entry'], ['id'])
    op.drop_column('links', 'entry_id')
    # ### end Alembic commands ###
