"""Translation state

Revision ID: 5f4dd9ce74f4
Revises: ab6f7c321ab4
Create Date: 2022-02-14 19:34:06.672782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4dd9ce74f4'
down_revision = 'ab6f7c321ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_states_id'), 'translation_states', ['id'], unique=False)
    op.add_column('translations', sa.Column('state', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'translations', 'translation_states', ['state'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'translations', type_='foreignkey')
    op.drop_column('translations', 'state')
    op.drop_index(op.f('ix_translation_states_id'), table_name='translation_states')
    op.drop_table('translation_states')
    # ### end Alembic commands ###
