"""Everything

Revision ID: ab6f7c321ab4
Revises: 78617b85fcda
Create Date: 2022-02-11 23:39:34.388884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6f7c321ab4'
down_revision = '78617b85fcda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lemma', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_id'), 'entries', ['id'], unique=False)
    op.create_index(op.f('ix_entries_lemma'), 'entries', ['lemma'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_id'), 'links', ['id'], unique=False)
    op.create_index(op.f('ix_links_url'), 'links', ['url'], unique=True)
    op.create_table('category_to_entry',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('entry_id', 'category_id')
    )
    op.create_table('english',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('link_to_entry',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('entry_id', 'link_id')
    )
    op.create_table('relation',
    sa.Column('entry1', sa.Integer(), nullable=False),
    sa.Column('entry2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry1'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['entry2'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('entry1', 'entry2')
    )
    op.create_table('slovene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alt_form', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestions',
    sa.Column('parent', sa.Integer(), nullable=False),
    sa.Column('child', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['parent'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('parent', 'child')
    )
    op.create_table('translations',
    sa.Column('parent', sa.Integer(), nullable=False),
    sa.Column('child', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['parent'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('parent', 'child')
    )
    op.drop_constraint('role_to_user_role_id_fkey', 'role_to_user', type_='foreignkey')
    op.drop_constraint('role_to_user_user_id_fkey', 'role_to_user', type_='foreignkey')
    op.create_foreign_key(None, 'role_to_user', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_to_user', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_to_user', type_='foreignkey')
    op.drop_constraint(None, 'role_to_user', type_='foreignkey')
    op.create_foreign_key('role_to_user_user_id_fkey', 'role_to_user', 'users', ['user_id'], ['id'])
    op.create_foreign_key('role_to_user_role_id_fkey', 'role_to_user', 'roles', ['role_id'], ['id'])
    op.drop_table('translations')
    op.drop_table('suggestions')
    op.drop_table('slovene')
    op.drop_table('relation')
    op.drop_table('link_to_entry')
    op.drop_table('english')
    op.drop_table('category_to_entry')
    op.drop_index(op.f('ix_links_url'), table_name='links')
    op.drop_index(op.f('ix_links_id'), table_name='links')
    op.drop_table('links')
    op.drop_table('events')
    op.drop_index(op.f('ix_entries_lemma'), table_name='entries')
    op.drop_index(op.f('ix_entries_id'), table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
