"""Add cascade removal

Revision ID: ca3a01bab94d
Revises: f8e061c471e6
Create Date: 2022-02-19 21:29:28.736999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3a01bab94d'
down_revision = 'f8e061c471e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_to_entry_category_id_fkey', 'category_to_entry', type_='foreignkey')
    op.drop_constraint('category_to_entry_entry_id_fkey', 'category_to_entry', type_='foreignkey')
    op.create_foreign_key(None, 'category_to_entry', 'entries', ['entry_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'category_to_entry', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('english_id_fkey', 'english', type_='foreignkey')
    op.create_foreign_key(None, 'english', 'entries', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('relations_entry1_fkey', 'relations', type_='foreignkey')
    op.drop_constraint('relations_entry2_fkey', 'relations', type_='foreignkey')
    op.create_foreign_key(None, 'relations', 'entries', ['entry1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'relations', 'entries', ['entry2'], ['id'], ondelete='CASCADE')
    op.drop_constraint('slovene_id_fkey', 'slovene', type_='foreignkey')
    op.create_foreign_key(None, 'slovene', 'entries', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('suggestions_child_fkey', 'suggestions', type_='foreignkey')
    op.drop_constraint('suggestions_parent_fkey', 'suggestions', type_='foreignkey')
    op.create_foreign_key(None, 'suggestions', 'entries', ['child'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'suggestions', 'entries', ['parent'], ['id'], ondelete='CASCADE')
    op.drop_constraint('translations_state_fkey', 'translations', type_='foreignkey')
    op.drop_constraint('translations_parent_fkey', 'translations', type_='foreignkey')
    op.drop_constraint('translations_child_fkey', 'translations', type_='foreignkey')
    op.create_foreign_key(None, 'translations', 'entries', ['child'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'translations', 'entries', ['parent'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'translations', 'translation_states', ['state'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'translations', type_='foreignkey')
    op.drop_constraint(None, 'translations', type_='foreignkey')
    op.drop_constraint(None, 'translations', type_='foreignkey')
    op.create_foreign_key('translations_child_fkey', 'translations', 'entries', ['child'], ['id'])
    op.create_foreign_key('translations_parent_fkey', 'translations', 'entries', ['parent'], ['id'])
    op.create_foreign_key('translations_state_fkey', 'translations', 'translation_states', ['state'], ['id'])
    op.drop_constraint(None, 'suggestions', type_='foreignkey')
    op.drop_constraint(None, 'suggestions', type_='foreignkey')
    op.create_foreign_key('suggestions_parent_fkey', 'suggestions', 'entries', ['parent'], ['id'])
    op.create_foreign_key('suggestions_child_fkey', 'suggestions', 'entries', ['child'], ['id'])
    op.drop_constraint(None, 'slovene', type_='foreignkey')
    op.create_foreign_key('slovene_id_fkey', 'slovene', 'entries', ['id'], ['id'])
    op.drop_constraint(None, 'relations', type_='foreignkey')
    op.drop_constraint(None, 'relations', type_='foreignkey')
    op.create_foreign_key('relations_entry2_fkey', 'relations', 'entries', ['entry2'], ['id'])
    op.create_foreign_key('relations_entry1_fkey', 'relations', 'entries', ['entry1'], ['id'])
    op.drop_constraint(None, 'english', type_='foreignkey')
    op.create_foreign_key('english_id_fkey', 'english', 'entries', ['id'], ['id'])
    op.drop_constraint(None, 'category_to_entry', type_='foreignkey')
    op.drop_constraint(None, 'category_to_entry', type_='foreignkey')
    op.create_foreign_key('category_to_entry_entry_id_fkey', 'category_to_entry', 'entries', ['entry_id'], ['id'])
    op.create_foreign_key('category_to_entry_category_id_fkey', 'category_to_entry', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
