"""Rename relation to relations

Revision ID: f8e061c471e6
Revises: 3b81be27e52c
Create Date: 2022-02-16 22:40:29.855833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e061c471e6'
down_revision = '3b81be27e52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relations',
    sa.Column('entry1', sa.Integer(), nullable=False),
    sa.Column('entry2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry1'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['entry2'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('entry1', 'entry2')
    )
    op.drop_table('relation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation',
    sa.Column('entry1', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry2', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['entry1'], ['entries.id'], name='relation_entry1_fkey'),
    sa.ForeignKeyConstraint(['entry2'], ['entries.id'], name='relation_entry2_fkey'),
    sa.PrimaryKeyConstraint('entry1', 'entry2', name='relation_pkey')
    )
    op.drop_table('relations')
    # ### end Alembic commands ###
