# Generated by Django 3.2.6 on 2021-09-07 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('abbr', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=100)),
                ('separate_gender_form', models.BooleanField()),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TranslationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=100)),
                ('use_case', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnglishEntry',
            fields=[
                ('word_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='leksikon.word')),
                ('translation_comment', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='leksikon.Category')),
                ('links', models.ManyToManyField(blank=True, to='leksikon.Link')),
                ('suggestions', models.ManyToManyField(blank=True, to='leksikon.Suggestion')),
                ('translation_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leksikon.translationstate')),
            ],
            options={
                'verbose_name_plural': 'English entries',
            },
            bases=('leksikon.word',),
        ),
        migrations.CreateModel(
            name='SloveneEntry',
            fields=[
                ('word_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='leksikon.word')),
                ('separate_gender_form', models.BooleanField()),
                ('type', models.CharField(max_length=100)),
                ('female_form', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('leksikon.word',),
        ),
        migrations.CreateModel(
            name='RelatedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('related_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_related', to='leksikon.englishentry')),
                ('source_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_source', to='leksikon.englishentry')),
            ],
            options={
                'verbose_name_plural': 'Related entries',
            },
        ),
        migrations.CreateModel(
            name='GenderVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leksikon.gender')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leksikon.sloveneentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='englishentry',
            name='translations',
            field=models.ManyToManyField(blank=True, to='leksikon.SloveneEntry'),
        ),
    ]
