# Generated by Django 3.2.6 on 2021-08-22 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EnglishEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=100)),
                ('use_case', models.TextField()),
                ('translation_comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('abbr', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GenderVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leksikon.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=100)),
                ('separate_gender_form', models.BooleanField()),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=100)),
                ('separate_gender_form', models.BooleanField()),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('translation_female', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Translation2GenderVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leksikon.gendervariant')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leksikon.translation')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('related_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_entry_related', to='leksikon.englishentry')),
                ('source_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_entry_source', to='leksikon.englishentry')),
            ],
        ),
        migrations.AddField(
            model_name='gendervariant',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leksikon.translation'),
        ),
        migrations.CreateModel(
            name='Entry2Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leksikon.englishentry')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leksikon.translation')),
            ],
        ),
        migrations.CreateModel(
            name='Entry2Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leksikon.englishentry')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leksikon.suggestion')),
            ],
        ),
        migrations.CreateModel(
            name='Entry2Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leksikon.englishentry')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leksikon.link')),
            ],
        ),
        migrations.CreateModel(
            name='Entry2Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leksikon.category')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leksikon.englishentry')),
            ],
        ),
        migrations.AddField(
            model_name='englishentry',
            name='translation_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leksikon.translationstate'),
        ),
    ]
