# Generated by Django 3.2.6 on 2021-08-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leksikon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='englishentry',
            options={'verbose_name_plural': 'English entries'},
        ),
        migrations.AlterModelOptions(
            name='relatedentry',
            options={'verbose_name_plural': 'Related entries'},
        ),
        migrations.AlterField(
            model_name='englishentry',
            name='translation_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
