# Generated by Django 3.2.6 on 2021-09-09 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leksikon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leksikon.word')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='sloveneentry',
            options={'verbose_name_plural': 'Slovene entries'},
        ),
        migrations.AddField(
            model_name='englishentry',
            name='related',
            field=models.ManyToManyField(blank=True, to='leksikon.EnglishEntry'),
        ),
        migrations.DeleteModel(
            name='RelatedEntry',
        ),
    ]
