# Generated by Django 3.2.6 on 2021-08-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leksikon', '0002_auto_20210825_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishentry',
            name='categories',
            field=models.ManyToManyField(to='leksikon.Category'),
        ),
    ]
