# Generated by Django 3.2.6 on 2021-09-10 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leksikon', '0002_auto_20210909_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englishentry',
            name='related',
        ),
        migrations.AddField(
            model_name='word',
            name='related',
            field=models.ManyToManyField(blank=True, to='leksikon.Word'),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
