# Generated by Django 3.2.6 on 2021-08-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leksikon', '0003_englishentry_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry2link',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='entry2link',
            name='link',
        ),
        migrations.RemoveField(
            model_name='entry2suggestion',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='entry2suggestion',
            name='suggestion',
        ),
        migrations.RemoveField(
            model_name='entry2translation',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='entry2translation',
            name='translation',
        ),
        migrations.RemoveField(
            model_name='translation2gendervariant',
            name='gender_variant',
        ),
        migrations.RemoveField(
            model_name='translation2gendervariant',
            name='translation',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='translation_female',
        ),
        migrations.AddField(
            model_name='englishentry',
            name='links',
            field=models.ManyToManyField(to='leksikon.Link'),
        ),
        migrations.AddField(
            model_name='englishentry',
            name='suggestions',
            field=models.ManyToManyField(to='leksikon.Suggestion'),
        ),
        migrations.AddField(
            model_name='englishentry',
            name='translations',
            field=models.ManyToManyField(to='leksikon.Translation'),
        ),
        migrations.DeleteModel(
            name='Entry2Category',
        ),
        migrations.DeleteModel(
            name='Entry2Link',
        ),
        migrations.DeleteModel(
            name='Entry2Suggestion',
        ),
        migrations.DeleteModel(
            name='Entry2Translation',
        ),
        migrations.DeleteModel(
            name='Translation2GenderVariant',
        ),
    ]
