# Generated by Django 3.2.6 on 2021-08-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leksikon', '0005_auto_20210827_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishentry',
            name='categories',
            field=models.ManyToManyField(blank=True, to='leksikon.Category'),
        ),
        migrations.AlterField(
            model_name='englishentry',
            name='links',
            field=models.ManyToManyField(blank=True, to='leksikon.Link'),
        ),
        migrations.AlterField(
            model_name='englishentry',
            name='suggestions',
            field=models.ManyToManyField(blank=True, to='leksikon.Suggestion'),
        ),
        migrations.AlterField(
            model_name='englishentry',
            name='translations',
            field=models.ManyToManyField(blank=True, to='leksikon.Translation'),
        ),
    ]
