# Generated by Django 3.2.6 on 2021-08-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leksikon', '0006_auto_20210827_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='female_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
